# Generated by Django 3.2.25 on 2024-06-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20240613_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.IntegerField(default='00', unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=300, unique=True),
        ),
    ]
