# Generated by Django 3.2.25 on 2024-06-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240613_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='prints_size',
            new_name='selected_size',
        ),
    ]
