# Generated by Django 3.2.25 on 2024-06-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20240625_1053'),
        ('checkout', '0003_rename_prints_size_orderlineitem_selected_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineitems', to='checkout.order'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='prints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.prints'),
        ),
    ]
