# Generated by Django 3.2.25 on 2024-05-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=150, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('a4_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('a5_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.photo')),
            ],
            options={
                'verbose_name_plural': 'Prints',
            },
        ),
    ]
