# Generated by Django 3.2.25 on 2024-05-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='project',
            new_name='project_names',
        ),
        migrations.AddField(
            model_name='print',
            name='sku',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
