# Generated by Django 3.2.25 on 2024-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20240520_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='has_sizes',
        ),
        migrations.AddField(
            model_name='print',
            name='sizes',
            field=models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], default='A4', max_length=3),
        ),
    ]
