# Generated by Django 3.2.25 on 2024-06-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20240613_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prints',
            name='a4_price',
            field=models.DecimalField(decimal_places=2, default=120.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prints',
            name='a5_price',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='prints',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='prints',
            name='friendly_name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='prints',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='prints',
            name='image_url',
            field=models.URLField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='prints',
            name='limited_edition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prints',
            name='sku',
            field=models.CharField(default='00', max_length=150, unique=True),
        ),
    ]
