# Generated by Django 3.2.25 on 2024-06-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20240613_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='prints',
            name='has_sizes',
            field=models.BooleanField(default=True),
        ),
    ]
