# Generated by Django 3.2.25 on 2024-05-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20240518_1328'),
        ('shop', '0003_auto_20240520_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='project_names',
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
