# Generated by Django 3.2.25 on 2024-05-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20240518_1328'),
        ('shop', '0004_auto_20240520_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Print',
            new_name='ShopPrint',
        ),
    ]
