# Generated by Django 3.2.25 on 2024-06-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20240625_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prints',
            name='sku',
            field=models.IntegerField(default='00', unique=True),
        ),
    ]
