# Generated by Django 3.2.25 on 2024-05-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20240518_1328'),
        ('shop', '0005_rename_print_shopprint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopPrint',
            new_name='Prints',
        ),
    ]
